export const Paths = {
  Home: '/',
  AllProducts: (type: string): string => `/all-products/${type}`,
  AllBrands: (type: string): string => `/all-brands/${type}`,
  CategoryPage: (type: string): string => `/category/${type}`,
  Cart: '/cart',
  ProductDetail: (id: string): string => `/product/${id}`,
  Profile: '/profile',
  Address: '/profile/address',
  Password: '/profile/password',
  History: '/history',
  Reviews: '/reviews',
  Notifications: '/notifications',
  Orders: '/orders',
  OrderDetail: (id: string): string => `/orders/${id}`,
  OrderTracking: (id: string): string => `/orders/${id}/tracking`,
  Return: '/return',
  Wallet: '/wallet',
  TransferCoin: '/transfer-coin',
  ChargeCoin: '/charge-coin',
  ChargeCoinTransferInformation: '/charge-coin/transfer-information',
};
